import type {Metadata} from 'next';
import Link from 'next/link';
import {ArrowUpRight,MessageCircle} from 'lucide-react';
import {CTA,PageHero} from '@/components/Site';
import {whatsappLink} from '@/lib/data';

export const metadata:Metadata={title:'Halal Fast Food in Weligama | Burgers & Chicken',description:'Looking for halal food in Weligama? Explore COFFIYANO\'s halal burgers, submarines, broasted chicken and refreshing drinks. Visit us or order free Weligama delivery.',alternates:{canonical:'/halal-food-weligama'}};

export default function Halal(){return <><PageHero eyebrow="Halal food in Weligama" title="Good food, with peace of mind." description="Coffiyano is here for an easy, flavour-packed halal meal - whether you are visiting Weligama or already call it home."/><section className="section halal-page"><div className="container halal-grid"><div className="halal-photo"><img src="/images/food-2.jpeg" alt="Food served at Coffiyano in Weligama"/><span>Halal food</span></div><div><span className="eyebrow">What this means here</span><h2>Fresh, full of flavour and made to our halal requirements.</h2><p>We confirm that our food, ingredients and preparation comply with our halal requirements. Coffiyano does not hold a formal halal certificate.</p><p>Have a specific dietary question? Our team is happy to help before you order.</p><div className="hero-actions"><Link className="btn" href="/menu">Explore the menu <ArrowUpRight size={16}/></Link><a className="text-link" href={whatsappLink('Hello COFFIYANO! I have a question about halal ingredients and would like to order.')} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/> Ask on WhatsApp</a></div></div></div></section><section className="halal-questions"><div className="container"><span className="eyebrow">Before you visit</span><h2>A few quick answers.</h2><div className="question-grid"><article><b>Is Coffiyano halal-certified?</b><p>No. Our food and preparation meet our halal requirements, but we do not hold a formal halal certificate.</p></article><article><b>Can I ask about ingredients?</b><p>Yes. Message us before ordering and we will help with current ingredient or preparation questions.</p></article><article><b>Do you deliver in Weligama?</b><p>Yes. Delivery is free across Weligama; send your location so our team can confirm availability.</p></article></div><CTA message="Hello COFFIYANO! I have a question about halal ingredients and would like to order."/></div></section></>}
