import type {Metadata} from 'next';
import Link from 'next/link';
import {ArrowUpRight,MapPin} from 'lucide-react';
import {PageHero} from '@/components/Site';
import {business} from '@/lib/data';

export const metadata:Metadata={title:'About Our Restaurant',description:'Discover COFFIYANO, a welcoming halal fast-food restaurant in Weligama, Sri Lanka, serving burgers, submarines, crispy chicken and fresh drinks.',alternates:{canonical:'/about'}};

export default function About(){return <><PageHero eyebrow="A little about us" title="Fresh food, friendly faces." description="Coffiyano is a relaxed food stop in Weligama for local regulars, beachgoers and anyone ready for something delicious."/><section className="about-story section"><div className="container about-grid"><div className="about-image"><img src="/images/storefront-side.webp" alt="Coffiyano street-facing storefront"/><span>Since the first bite</span></div><div><span className="eyebrow">The Coffiyano way</span><h2>Simple things, done with care.</h2><p>We make comforting fast food that feels generous, familiar and full of flavour. Think burgers, submarines, crispy chicken, snacks, milkshakes and freshly blended juices.</p><p>Our food and preparation meet our halal requirements. We do not hold a formal halal certificate.</p><a className="text-link" href={business.maps} target="_blank" rel="noopener noreferrer"><MapPin size={17}/> Come find us in Weligama <ArrowUpRight size={16}/></a></div></div></section><section className="about-values"><div className="container values-grid"><article><b>01</b><h3>Easy to love</h3><p>Comfort food with the flavours you reach for again and again.</p></article><article><b>02</b><h3>Open late</h3><p>Because good food should still be around when the day runs long.</p></article><article><b>03</b><h3>Close to home</h3><p>Free delivery across Weligama, straight from our kitchen to you.</p></article></div></section><section className="section container about-end"><h2>See you around<br/><em>the table.</em></h2><Link className="btn" href="/menu">See what&apos;s cooking <ArrowUpRight size={16}/></Link></section></>}
