'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,MapPin,MessageCircle,Phone,Star} from 'lucide-react';
import {business,whatsappLink,categories,money} from '@/lib/data';

const links=[['/menu','Menu'],['/halal-food-weligama','Halal food'],['/about','Our story'],['/gallery','Gallery'],['/reviews','Reviews'],['/location','Find us']];

function Brand({footer=false}:{footer?:boolean}){return <Link className={`brand${footer?' brand-footer':''}`} href="/" aria-label="Coffiyano home"><span>COFFIYANO</span></Link>}

export function Header(){return <><div className="header-note"><div className="container"><span>Weligama, Sri Lanka</span><span>Halal fast food - free local delivery</span></div></div><header className="header"><div className="container header-inner"><Brand/><nav className="nav" aria-label="Main navigation">{links.map(([url,label])=><Link key={url} href={url}>{label}</Link>)}</nav><a className="header-order" href={whatsappLink()} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/> Order now <ArrowUpRight size={15}/></a></div></header><div className="mobile-action"><Link href="/menu">Menu</Link><a href={business.maps} target="_blank" rel="noopener noreferrer">Directions</a><a href={whatsappLink()} target="_blank" rel="noopener noreferrer">Order</a></div></>}

export function Footer(){return <footer className="footer"><div className="container"><div className="footer-top"><Brand footer/><p>Fresh comfort food, late-night cravings and good energy in the heart of Weligama.</p><a className="footer-social" href={business.instagram} target="_blank" rel="noopener noreferrer">Follow our kitchen <ArrowUpRight size={15}/></a></div><div className="footer-grid"><div><span className="footer-label">Come by</span><p>{business.address}</p><a href={business.maps} target="_blank" rel="noopener noreferrer"><MapPin size={16}/> Get directions</a></div><div><span className="footer-label">Open late</span><p>Mon-Thu & Sat-Sun<br/>10:30 AM - 1:00 AM</p><p>Friday<br/>3:00 PM - 1:00 AM</p></div><div><span className="footer-label">Contact</span><a href={`tel:${business.telephone}`}><Phone size={16}/> {business.displayPhone}</a><a href={whatsappLink()} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/> WhatsApp orders</a></div><div><span className="footer-label">Explore</span>{links.slice(0,4).map(([url,label])=><Link key={url} href={url}>{label}</Link>)}</div></div><div className="footer-bottom"><span>Copyright {new Date().getFullYear()} Coffiyano</span><span>Fresh and tasty, Weligama</span></div></div></footer>}

export function CTA({message='Hello COFFIYANO! I would like to order food for free delivery in Weligama.'}:{message?:string}){return <section className="callout"><div className="callout-mark">C</div><div><span className="eyebrow">Your table is waiting</span><h3>Hungry now? We deliver across Weligama.</h3><p>Send us your order and location on WhatsApp. We will take it from there.</p></div><a className="btn btn-light" href={whatsappLink(message)} target="_blank" rel="noopener noreferrer">Start an order <ArrowUpRight size={16}/></a></section>}

export function MenuBrowser(){const [active,setActive]=useState(0);const category=categories[active];return <><div className="menu-browser-head"><div><span className="eyebrow">Pick a craving</span><h2>{category.name}</h2></div><span className="menu-count">{category.items.length} choices</span></div><div className="tabs" role="group" aria-label="Food categories">{categories.map((c,i)=><button key={c.name} type="button" className={`tab ${i===active?'active':''}`} onClick={()=>setActive(i)} aria-pressed={i===active}>{c.name}</button>)}</div><div className="menu-list">{category.items.map(([name,price],i)=><article className="menu-item" key={name}><span className="menu-number">{String(i+1).padStart(2,'0')}</span><strong>{name}</strong><span>{money(price)}</span></article>)}</div><CTA message={`Hello COFFIYANO! I'd like to order from your ${category.name} menu for free delivery in Weligama.`}/></>}

type Review={name:string;rating:number;text:string;relativePublishTimeDescription?:string;authorUrl?:string;googleMapsUri?:string};
type ReviewPayload={rating?:number;count?:number;reviews?:Review[];mapsUrl?:string;error?:string};

export function Reviews({compact=false}:{compact?:boolean}){const [data,setData]=useState<ReviewPayload|null>(null);useEffect(()=>{const controller=new AbortController();fetch('/api/google-reviews',{signal:controller.signal}).then(r=>r.json()).then(setData).catch(()=>{});return()=>controller.abort()},[]);const visible=data?.reviews?.slice(0,compact?3:6);return <><div className="review-heading"><div><span className="eyebrow">From our guests</span><h2>Good food gets talked about.</h2></div><div className="review-rating">{data?.rating!==undefined?<><Star size={18} fill="currentColor"/> <strong>{data.rating.toFixed(1)}</strong><span>/ 5 from {data.count?.toLocaleString()} guests</span></>:<><Star size={18} fill="currentColor"/><span>Read our Google reviews</span></>}</div></div>{visible?.length?<div className="reviews-grid">{visible.map((review,i)=><article className="review-card" key={i}><div className="review-stars" aria-label={`${review.rating} out of 5 stars`}>{Array.from({length:Math.max(0,Math.min(5,review.rating))},(_,star)=><Star key={star} size={15} fill="currentColor"/>)}</div><p>&quot;{review.text}&quot;</p><div className="review-author">{review.authorUrl?<a href={review.authorUrl} target="_blank" rel="noopener noreferrer">{review.name}</a>:review.name}<span>{review.relativePublishTimeDescription}</span></div></article>)}</div>:<article className="review-empty"><span className="review-quote">&ldquo;</span><p>Every visit should feel worth repeating. See what guests are saying on Google.</p><a className="text-link" href={business.maps} target="_blank" rel="noopener noreferrer">Read real guest reviews <ArrowUpRight size={15}/></a></article>}<a className="text-link review-more" href={data?.mapsUrl||business.maps} target="_blank" rel="noopener noreferrer">More on Google Maps <ArrowUpRight size={15}/></a></>}

export function PageHero({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <section className="page-intro"><div className="container page-intro-inner"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="page-intro-stamp"><span>COFFIYANO</span><b>WELIGAMA</b><small>FRESH + TASTY</small></div></div></section>}
