'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {business,whatsappLink,categories,money} from '@/lib/data';
const links=[['/menu','Menu'],['/halal-food-weligama','Halal food'],['/about','Our story'],['/gallery','Gallery'],['/reviews','Reviews'],['/location','Find us']];
export function Header(){return <><header className="header"><div className="container header-inner"><Link className="brand" href="/">COFFIYANO<span>FRESH & TASTY</span></Link><nav className="nav" aria-label="Main navigation">{links.map(([url,label])=><Link key={url} href={url}>{label}</Link>)}</nav><a className="btn small" href={whatsappLink()} target="_blank" rel="noopener noreferrer">Order on WhatsApp ↗</a></div></header><div className="mobile-action"><Link href="/menu">View menu</Link><a href={business.maps} target="_blank" rel="noopener noreferrer">Directions ↗</a><a href={whatsappLink()} target="_blank" rel="noopener noreferrer">Order ↗</a></div></>}
export function Footer(){return <footer className="footer"><div className="container"><div className="footer-grid"><div><Link href="/" className="brand">COFFIYANO<span>FRESH & TASTY</span></Link><p>Halal fast food, refreshing drinks and a warm welcome in Weligama, Sri Lanka. Free delivery across Weligama.</p><a href={business.instagram} target="_blank" rel="noopener noreferrer">Instagram ↗</a></div><div><span className="eyebrow">Explore</span>{links.map(([url,label])=><Link key={url} href={url}>{label}</Link>)}<Link href="/contact">Contact</Link></div><div><span className="eyebrow">Visit</span><p>{business.address}</p><a href={`tel:${business.telephone}`}>{business.displayPhone}</a><a href={business.maps} target="_blank" rel="noopener noreferrer">Open Google Maps ↗</a><p>Mon–Thu & Sat–Sun: 10:30 AM–1:00 AM<br/>Friday: 3:00 PM–1:00 AM<br/><small>Closing at 1:00 AM the following day.</small></p></div></div><div className="footer-bottom">© {new Date().getFullYear()} COFFIYANO · Weligama, Sri Lanka · Prices and availability may change.</div></div></footer>}
export function CTA({message='Hello COFFIYANO! I would like to order food for free delivery in Weligama.'}:{message?:string}){return <div className="order-bar"><div><span className="eyebrow">Something delicious is calling</span><h3 style={{margin:'7px 0'}}>Order on WhatsApp · Free delivery across Weligama</h3><span className="note">Confirm your address and availability with our team.</span></div><a className="btn" href={whatsappLink(message)} target="_blank" rel="noopener noreferrer">Order via WhatsApp ↗</a></div>}
export function MenuBrowser(){const [active,setActive]=useState(0);return <><div className="tabs" role="group" aria-label="Food categories">{categories.map((c,i)=><button key={c.name} type="button" className={`tab ${i===active?'active':''}`} onClick={()=>setActive(i)} aria-pressed={i===active}>{c.name}</button>)}</div><div className="menu-list">{categories[active].items.map(([name,price])=><div className="menu-item" key={name}><strong>{name}</strong><span>{money(price)}</span></div>)}</div><CTA message={`Hello COFFIYANO! I'd like to order from your ${categories[active].name} menu for free delivery in Weligama.`}/></>}
type Review={name:string;rating:number;text:string;relativePublishTimeDescription?:string;authorUrl?:string;googleMapsUri?:string};type ReviewPayload={rating?:number;count?:number;reviews?:Review[];mapsUrl?:string;error?:string};
export function Reviews({compact=false}:{compact?:boolean}){const [data,setData]=useState<ReviewPayload|null>(null);useEffect(()=>{const controller=new AbortController();fetch('/api/google-reviews',{signal:controller.signal}).then(r=>r.json()).then(setData).catch(()=>{});return()=>controller.abort()},[]);return <><div className="section-top"><div><span className="eyebrow">Straight from our guests</span><h2>Good food. Real reviews.</h2>{data?.rating!==undefined&&<p className="muted"><span className="star">★</span> {data.rating.toFixed(1)} / 5 · {data.count?.toLocaleString()} Google ratings</p>}</div><a className="btn outline" href={data?.mapsUrl||business.maps} target="_blank" rel="noopener noreferrer">Read reviews on Google ↗</a></div>{data?.reviews?.length?<div className="reviews-grid">{data.reviews.slice(0,compact?3:5).map((r,i)=><article className="review-card" key={i}><div className="star" aria-label={`${r.rating} out of 5 stars`}>{'★'.repeat(Math.max(0,Math.min(5,r.rating)))}</div><p>{r.text}</p><div className="review-footer">{r.authorUrl?<a href={r.authorUrl} target="_blank" rel="noopener noreferrer">{r.name} ↗</a>:r.name}{r.relativePublishTimeDescription?` · ${r.relativePublishTimeDescription}`:''}</div><a className="review-source" href={r.googleMapsUri||data.mapsUrl||business.maps} target="_blank" rel="noopener noreferrer">Source: Google Maps ↗</a></article>)}</div>:<div className="review-card"><p>Explore authentic guest feedback on our Google Maps listing.</p><p className="note">Live reviews will display here after the Google Places API key and verified Place ID are configured.</p><a className="btn outline" href={business.maps} target="_blank" rel="noopener noreferrer">See genuine Google reviews ↗</a></div>}<p className="note" style={{marginTop:18}}>Google review content and ratings are provided by Google. Individual review availability and selection are determined by the Places API.</p></>}
export function PageHero({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></section>}
